import { useState } from 'react';
import { motion } from 'motion/react';
import {
  Shield, FileText, Cookie, Lock, X,
  Mail, Phone, MapPin, ArrowRight,
  Linkedin, Twitter, Instagram, Github,
} from 'lucide-react';

// ─── Types ───────────────────────────────────────────────────────────────────
type ModalKey = 'privacy' | 'terms' | 'cookie' | 'security' | null;

interface ModalContent {
  icon: React.ReactNode;
  title: string;
  subtitle: string;
  lastUpdated: string;
  accentColor: string;
  sections: { heading: string; body: React.ReactNode }[];
}

// ─── Modal Data ───────────────────────────────────────────────────────────────
const modalData: Record<Exclude<ModalKey, null>, ModalContent> = {
  privacy: {
    icon: <Shield className="w-5 h-5" />,
    title: 'Privacy Policy',
    subtitle: 'How we collect, use and protect your data',
    lastUpdated: 'February 1, 2026',
    accentColor: '#00b8d4',
    sections: [
      {
        heading: '1. Information We Collect',
        body: (
          <>
            <p className="text-slate-400 mb-3 text-sm leading-relaxed">
              TrustLayer collects information necessary to operate its behavioural trust intelligence platform:
            </p>
            <ul className="space-y-2 text-slate-400 text-sm">
              {[
                'Candidate profile data: name, contact details, resume, behavioural assessments',
                'HR user account information: name, email, role, login timestamps',
                'Trust scores and behavioural signals generated by the AI engine',
                'Interview feedback, notes and scoring data entered by your team',
                'Activity logs: actions taken within the platform, stage transitions',
                'Device and browser metadata for security and session management',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2.5">
                  <span className="w-1.5 h-1.5 rounded-full flex-shrink-0 mt-2" style={{ background: '#00b8d4' }} />
                  {item}
                </li>
              ))}
            </ul>
          </>
        ),
      },
      {
        heading: '2. How We Use Your Information',
        body: (
          <ul className="space-y-2 text-slate-400 text-sm">
            {[
              'Providing and operating the TrustLayer platform',
              'Generating behavioural trust scores and AI-driven candidate insights',
              'Enabling candidate pipeline tracking and onboarding workflows',
              'Sending automated notifications and alerts within the platform',
              'Improving platform performance, reliability and feature quality',
            ].map((item, i) => (
              <li key={i} className="flex items-start gap-2.5">
                <span className="w-1.5 h-1.5 rounded-full flex-shrink-0 mt-2" style={{ background: '#00b8d4' }} />
                {item}
              </li>
            ))}
          </ul>
        ),
      },
      {
        heading: '3. Data Storage & Security',
        body: <p className="text-slate-400 text-sm leading-relaxed">All data is stored on secure, encrypted cloud infrastructure. We apply TLS 1.3 in transit and AES-256 at rest. Regular backups ensure data integrity and availability.</p>,
      },
      {
        heading: '4. Data Sharing',
        body: <p className="text-slate-400 text-sm leading-relaxed">We do not sell, rent or share your organisation's recruitment data with third parties. Data may only be shared with integrations that you explicitly configure.</p>,
      },
      {
        heading: '5. Your Rights',
        body: <p className="text-slate-400 text-sm leading-relaxed">You have the right to access, correct or request deletion of your data. Contact us at <span className="font-semibold" style={{ color: '#00b8d4' }}>privacy@trustlayer.ai</span>. We respond within 30 days.</p>,
      },
    ],
  },
  terms: {
    icon: <FileText className="w-5 h-5" />,
    title: 'Terms of Service',
    subtitle: 'By using TrustLayer, you agree to these terms',
    lastUpdated: 'February 1, 2026',
    accentColor: '#7C3AED',
    sections: [
      { heading: '1. Acceptance of Terms', body: <p className="text-slate-400 text-sm leading-relaxed">By accessing or using TrustLayer, you agree to be bound by these Terms of Service. If using on behalf of an organisation, you confirm authority to bind that organisation.</p> },
      {
        heading: '2. Platform Usage',
        body: (
          <ul className="space-y-2 text-slate-400 text-sm">
            {['Managing candidate pipelines and hiring workflows', 'Accessing AI trust scores and behavioural analytics', 'Generating offer letters and managing onboarding', 'Accessing recruiter performance reports and dashboards', 'Assigning roles and managing team permissions'].map((item, i) => (
              <li key={i} className="flex items-start gap-2.5"><span className="w-1.5 h-1.5 rounded-full bg-violet-400 flex-shrink-0 mt-2" />{item}</li>
            ))}
          </ul>
        ),
      },
      { heading: '3. Account Responsibilities', body: <p className="text-slate-400 text-sm leading-relaxed">You are responsible for maintaining the confidentiality of your credentials. Notify us immediately of any unauthorised access.</p> },
      { heading: '4. Subscription & Billing', body: <p className="text-slate-400 text-sm leading-relaxed">Paid plans are billed per user per month as per the selected billing cycle. Cancellations take effect at end of the current billing period.</p> },
      { heading: '5. Intellectual Property', body: <p className="text-slate-400 text-sm leading-relaxed">All platform code and UI are the intellectual property of TrustLayer. Your organisation retains full ownership of its candidate data and content.</p> },
      { heading: '6. Limitation of Liability', body: <p className="text-slate-400 text-sm leading-relaxed">Platform provided on an "as-is" basis. Our total liability shall not exceed the amount paid in the 3 months preceding any claim.</p> },
    ],
  },
  cookie: {
    icon: <Cookie className="w-5 h-5" />,
    title: 'Cookie Policy',
    subtitle: 'How TrustLayer uses cookies and local storage',
    lastUpdated: 'February 1, 2026',
    accentColor: '#F59E0B',
    sections: [
      { heading: '1. What Are Cookies?', body: <p className="text-slate-400 text-sm leading-relaxed">Cookies are small text files stored on your device. We use them to keep you signed in, remember preferences, and understand platform usage.</p> },
      {
        heading: '2. Types of Cookies We Use',
        body: (
          <div className="space-y-3">
            {[
              { type: 'Essential', color: 'rgba(0,184,212,0.15)', textColor: '#00b8d4', desc: 'Required for login, sessions and security. Cannot be disabled.' },
              { type: 'Preference', color: 'rgba(124,58,237,0.15)', textColor: '#A78BFA', desc: 'Remember settings like pipeline filters and dashboard preferences.' },
              { type: 'Analytics', color: 'rgba(245,158,11,0.15)', textColor: '#FCD34D', desc: 'Aggregated, anonymous data that helps us improve the platform.' },
            ].map((c) => (
              <div key={c.type} className="rounded-xl p-4" style={{ background: c.color, border: `1px solid ${c.textColor}30` }}>
                <span className="text-xs font-bold mb-1.5 block" style={{ color: c.textColor }}>{c.type} Cookies</span>
                <p className="text-slate-400 text-sm">{c.desc}</p>
              </div>
            ))}
          </div>
        ),
      },
      { heading: '3. Managing Cookies', body: <p className="text-slate-400 text-sm leading-relaxed">You can control cookies via browser settings. Disabling essential cookies will affect login functionality. Contact <span className="font-semibold" style={{ color: '#00b8d4' }}>info@averlonworld.com</span> to opt out of analytics.</p> },
    ],
  },
  security: {
    icon: <Lock className="w-5 h-5" />,
    title: 'Security',
    subtitle: 'How we protect your data and platform',
    lastUpdated: 'February 1, 2026',
    accentColor: '#10B981',
    sections: [
      { heading: '1. Data Encryption', body: <p className="text-slate-400 text-sm leading-relaxed">All data in transit is encrypted using TLS 1.3. Data at rest uses AES-256 encryption including candidate data, credentials, and AI trust scores.</p> },
      {
        heading: '2. Access Control',
        body: (
          <ul className="space-y-2 text-slate-400 text-sm">
            {['Role-based access control (RBAC) — each user sees only what their role permits', 'Sensitive trust score data restricted by default', 'Session timeout after 30 minutes of inactivity', 'Secure password hashing using bcrypt with salt rounds'].map((item, i) => (
              <li key={i} className="flex items-start gap-2.5"><span className="w-1.5 h-1.5 rounded-full bg-emerald-400 flex-shrink-0 mt-2" />{item}</li>
            ))}
          </ul>
        ),
      },
      { heading: '3. Infrastructure', body: <p className="text-slate-400 text-sm leading-relaxed">Hosted on secure cloud infrastructure with automated daily backups, redundant storage and 99.9% uptime SLA on paid plans. Protected by firewalls and DDoS mitigation.</p> },
      { heading: '4. Incident Response', body: <p className="text-slate-400 text-sm leading-relaxed">In the event of a security incident, we will notify affected organisations within 72 hours. Report vulnerabilities to <span className="font-semibold" style={{ color: '#10B981' }}>security@trustlayer.ai</span>.</p> },
    ],
  },
};

// ─── Link Data ────────────────────────────────────────────────────────────────
const legalLinks: { key: Exclude<ModalKey, null>; label: string; icon: React.ReactNode }[] = [
  { key: 'privacy',  label: 'Privacy Policy',  icon: <Shield className="w-3.5 h-3.5" /> },
  { key: 'terms',    label: 'Terms of Service', icon: <FileText className="w-3.5 h-3.5" /> },
  { key: 'cookie',   label: 'Cookie Policy',    icon: <Cookie className="w-3.5 h-3.5" /> },
  { key: 'security', label: 'Security',         icon: <Lock className="w-3.5 h-3.5" /> },
];

const productLinks = [
  { label: 'Features',     id: 'features' },
  { label: 'AI Engine',    id: 'ai-engine' },
  { label: 'Dashboard',    id: 'dashboard' }
];





const C = {
  accent: '#00b8d4',
};

// ─── Component ────────────────────────────────────────────────────────────────
export default function Footer() {
  const [activeModal, setActiveModal] = useState<ModalKey>(null);
  const modal = activeModal ? modalData[activeModal] : null;

  const scrollToSection = (id: string) => {
    const el = document.getElementById(id);
    if (el) {
      window.scrollTo({ top: el.getBoundingClientRect().top + window.pageYOffset - 80, behavior: 'smooth' });
    }
  };

  return (
    <>
      <footer
        id="contact"
        style={{
          background: 'linear-gradient(180deg, #070B15 0%, #0A0E1A 60%, #060914 100%)',
          borderTop: `1px solid rgba(0,184,212,0.12)`,
          fontFamily: "'Inter', sans-serif",
        }}
      >
        {/* ── Main Grid ── */}
        <div style={{ maxWidth: 1280, margin: '0 auto', padding: '64px 32px 48px' }}>
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
            gap: 48,
          }}>

            {/* Col 1 — Brand */}
            <motion.div
              style={{ gridColumn: 'span 1' }}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
            >
              {/* Logo */}
              <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 18 }}>
                <div style={{
                  width: 38, height: 38, borderRadius: 10,
                  background: `linear-gradient(135deg, ${C.accent}, #0097b2)`,
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  boxShadow: '0 4px 14px rgba(0,184,212,0.25)',
                  flexShrink: 0,
                }}>
                  <span style={{ color: 'white', fontWeight: 800, fontSize: 15 }}>TL</span>
                </div>
                <span style={{ color: '#ffffff', fontWeight: 800, fontSize: 19, letterSpacing: '-0.03em' }}>TrustLayer</span>
              </div>

              <p style={{ fontSize: 13.5, color: 'rgba(255,255,255,0.4)', lineHeight: 1.7, margin: '0 0 24px', maxWidth: 230 }}>
                AI-powered behavioural trust intelligence for modern HR teams and recruitment platforms.
              </p>

              
              
            </motion.div>

            {/* Col 2 — Product */}
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.08 }}
            >
              <p style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: 'rgba(255,255,255,0.25)', marginBottom: 20 }}>
                Product
              </p>
              <ul style={{ listStyle: 'none', margin: 0, padding: 0 }}>
                {productLinks.map(link => (
                  <li key={link.id} style={{ marginBottom: 12 }}>
                    <button
                      onClick={() => scrollToSection(link.id)}
                      className="group"
                      style={{
                        background: 'none', border: 'none', cursor: 'pointer', padding: 0,
                        fontSize: 13.5, color: 'rgba(255,255,255,0.45)',
                        display: 'flex', alignItems: 'center', gap: 6,
                        transition: 'color 0.15s',
                      }}
                      onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.color = C.accent; }}
                      onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.color = 'rgba(255,255,255,0.45)'; }}
                    >
                      <ArrowRight style={{ width: 12, height: 12, color: C.accent, opacity: 0, transition: 'opacity 0.15s, transform 0.15s', transform: 'translateX(-4px)' }}
                        onMouseEnter={e => { (e.currentTarget as SVGElement).style.opacity = '1'; }}
                      />
                      {link.label}
                    </button>
                  </li>
                ))}
              </ul>
            </motion.div>

            {/* Col 4 — Legal */}
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.24 }}
            >
              <p style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: 'rgba(255,255,255,0.25)', marginBottom: 20 }}>
                Legal
              </p>
              <ul style={{ listStyle: 'none', margin: 0, padding: 0 }}>
                {legalLinks.map(link => (
                  <li key={link.key} style={{ marginBottom: 12 }}>
                    <button
                      onClick={() => setActiveModal(link.key)}
                      style={{
                        background: 'none', border: 'none', cursor: 'pointer', padding: 0,
                        fontSize: 13.5, color: 'rgba(255,255,255,0.45)',
                        display: 'flex', alignItems: 'center', gap: 8,
                        transition: 'color 0.15s',
                      }}
                      onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.color = C.accent; }}
                      onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.color = 'rgba(255,255,255,0.45)'; }}
                    >
                      <span style={{ color: C.accent, opacity: 0.6, display: 'flex' }}>{link.icon}</span>
                      {link.label}
                    </button>
                  </li>
                ))}
              </ul>
            </motion.div>

            {/* Col 5 — Contact */}
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.32 }}
            >
              <p style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: 'rgba(255,255,255,0.25)', marginBottom: 20 }}>
                Contact
              </p>
              <ul style={{ listStyle: 'none', margin: 0, padding: 0 }}>
                {[
                  { icon: <Mail style={{ width: 15, height: 15, flexShrink: 0 }} />, label: 'info@averlonworld.com', href: 'mailto:info@averlonworld.com' },
                  { icon: <Phone style={{ width: 15, height: 15, flexShrink: 0 }} />, label: '+91 98765 43210', href: 'tel:+919876543210' },
                  { icon: <MapPin style={{ width: 15, height: 15, flexShrink: 0 }} />, label: '5th Floor, Lodha Supremus - II,\n Phase - II, Unit No. A-533/A-515,\nRoad No. 22, Wagle Industrial Estate, Thane West, Maharashtra,\nIndia — 400001', href: null },
                ].map((item, i) => (
                  <li key={i} style={{ marginBottom: 16 }}>
                    {item.href ? (
                      <a
                        href={item.href}
                        style={{ display: 'flex', alignItems: 'flex-start', gap: 10, fontSize: 13.5, color: 'rgba(255,255,255,0.45)', textDecoration: 'none', transition: 'color 0.15s' }}
                        onMouseEnter={e => { (e.currentTarget as HTMLAnchorElement).style.color = C.accent; }}
                        onMouseLeave={e => { (e.currentTarget as HTMLAnchorElement).style.color = 'rgba(255,255,255,0.45)'; }}
                      >
                        <span style={{ color: C.accent, marginTop: 2, display: 'flex' }}>{item.icon}</span>
                        {item.label}
                      </a>
                    ) : (
                      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 10, fontSize: 13.5, color: 'rgba(255,255,255,0.45)' }}>
                        <span style={{ color: C.accent, marginTop: 2, display: 'flex', flexShrink: 0 }}>{item.icon}</span>
                        <span style={{ whiteSpace: 'pre-line' }}>{item.label}</span>
                      </div>
                    )}
                  </li>
                ))}
              </ul>

             
              
            </motion.div>
          </div>
        </div>

        {/* ── Bottom Strip ── */}
        <motion.div
          style={{ borderTop: '1px solid rgba(255,255,255,0.06)' }}
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.4 }}
        >
          <div style={{
            maxWidth: 1280, margin: '0 auto', padding: '20px 32px',
            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
            flexWrap: 'wrap', gap: 10,
          }}>
            <p style={{ fontSize: 12, color: 'white', margin: 0 }}>
              © {new Date().getFullYear()} TrustLayer. All rights reserved.
            </p>
            <p style={{ fontSize: 12, color: 'white', margin: 0 }}>
              Powered by{' '}
              <span style={{ fontWeight: 700, color: 'white' }}>Averlon</span>
            </p>
          </div>
        </motion.div>

        {/* Accent gradient line */}
        <div style={{ height: 2, background: `linear-gradient(90deg, transparent, ${C.accent}, transparent)` }} />
      </footer>

      {/* ── MODAL ── */}
      {modal && activeModal && (
        <div
          style={{
            position: 'fixed', inset: 0, zIndex: 50,
            display: 'flex', alignItems: 'flex-end',
            justifyContent: 'center',
            padding: 0,
            background: 'rgba(6,9,20,0.85)',
            backdropFilter: 'blur(8px)',
          }}
          onClick={() => setActiveModal(null)}
        >
          <style>{`@media (min-width: 640px) { .modal-inner { align-items: center !important; padding: 24px !important; } }`}</style>
          <div
            style={{
              position: 'relative', width: '100%', maxWidth: 672,
              borderRadius: '16px 16px 0 0',
              display: 'flex', flexDirection: 'column', overflow: 'hidden',
              background: '#0D1526',
              border: '1px solid rgba(255,255,255,0.08)',
              boxShadow: '0 32px 80px rgba(0,0,0,0.6)',
              maxHeight: '90vh',
            }}
            onClick={e => e.stopPropagation()}
          >
            {/* Accent top bar */}
            <div style={{ height: 2, background: `linear-gradient(90deg, ${modalData[activeModal].accentColor}, transparent)`, flexShrink: 0 }} />

            {/* Header */}
            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', padding: '24px 28px 20px', borderBottom: '1px solid rgba(255,255,255,0.06)', flexShrink: 0 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
                <div style={{
                  width: 40, height: 40, borderRadius: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
                  background: `${modalData[activeModal].accentColor}18`,
                  border: `1px solid ${modalData[activeModal].accentColor}30`,
                  color: modalData[activeModal].accentColor,
                }}>
                  {modal.icon}
                </div>
                <div>
                  <h2 style={{ color: '#fff', fontWeight: 800, fontSize: 18, margin: 0 }}>{modal.title}</h2>
                  <p style={{ color: 'rgba(255,255,255,0.35)', fontSize: 12, margin: '4px 0 0' }}>{modal.subtitle}</p>
                </div>
              </div>
              <button
                onClick={() => setActiveModal(null)}
                style={{
                  width: 32, height: 32, borderRadius: '50%', border: 'none', cursor: 'pointer',
                  background: 'rgba(255,255,255,0.06)', color: 'rgba(255,255,255,0.4)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
                  transition: 'background 0.15s',
                }}
                onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.background = 'rgba(255,255,255,0.12)'; }}
                onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = 'rgba(255,255,255,0.06)'; }}
              >
                <X style={{ width: 16, height: 16 }} />
              </button>
            </div>

            {/* Last updated badge */}
            <div style={{ padding: '16px 28px 4px', flexShrink: 0 }}>
              <span style={{
                display: 'inline-flex', alignItems: 'center', gap: 6,
                fontSize: 11, padding: '6px 12px', borderRadius: 999, fontWeight: 600,
                background: `${modalData[activeModal].accentColor}12`,
                border: `1px solid ${modalData[activeModal].accentColor}25`,
                color: modalData[activeModal].accentColor,
              }}>
                Last updated: {modal.lastUpdated}
              </span>
            </div>

            {/* Scrollable content */}
            <div style={{ overflowY: 'auto', padding: '20px 28px', flex: 1, scrollbarWidth: 'thin', scrollbarColor: 'rgba(255,255,255,0.1) transparent' }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
                {modal.sections.map((section, i) => (
                  <div key={i}>
                    <h3 style={{ color: 'rgba(255,255,255,0.85)', fontSize: 13, fontWeight: 700, margin: '0 0 12px', display: 'flex', alignItems: 'center', gap: 8 }}>
                      <span style={{ width: 3, height: 16, borderRadius: 2, background: modalData[activeModal].accentColor, flexShrink: 0, display: 'inline-block' }} />
                      {section.heading}
                    </h3>
                    <div style={{ paddingLeft: 12 }}>{section.body}</div>
                  </div>
                ))}
              </div>
              <div style={{ height: 16 }} />
            </div>

            {/* Modal footer */}
            <div style={{ padding: '20px 28px', borderTop: '1px solid rgba(255,255,255,0.06)', background: 'rgba(0,0,0,0.2)', flexShrink: 0 }}>
              <button
                onClick={() => setActiveModal(null)}
                style={{
                  padding: '10px 24px', borderRadius: 12, border: 'none', cursor: 'pointer',
                  fontWeight: 700, fontSize: 14, color: '#fff',
                  background: `linear-gradient(135deg, ${modalData[activeModal].accentColor}, ${modalData[activeModal].accentColor}BB)`,
                  boxShadow: `0 4px 16px ${modalData[activeModal].accentColor}30`,
                  transition: 'opacity 0.2s, transform 0.2s',
                }}
                onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.opacity = '0.9'; (e.currentTarget as HTMLButtonElement).style.transform = 'translateY(-1px)'; }}
                onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.opacity = '1'; (e.currentTarget as HTMLButtonElement).style.transform = 'none'; }}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      <style>{`
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.4; }
        }
      `}</style>
    </>
  );
}